name: Publish

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    strategy:
      matrix:
        arch: [ "ubuntu-latest" ]
        git-version: [ "2.38.4" ]
    runs-on: ${{ matrix.arch }}
    container: fascinated/docker-images:nodejs_20
    steps:
      # Checkout the branch
      - name: Checkout
        uses: https://github.com/actions/checkout@v3

      # Setup Docker BuildX
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v2

      # Login to Docker
      - name: Login to Repo
        uses: https://github.com/docker/login-action@v2
        with:
          registry: git.rainnny.club
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_TOKEN }}

      # Build & Push to Docker
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: git.rainnny.club/rainnny/licenseserver:latest